const NODE_ELEMENT_HEIGHT = 74;
const NODE_ELEMENT_WIDTH = 260;
const LABEL_ELEMENT_HEIGHT = 34;
const LABEL_ELEMENT_WIDTH = 100;

export {
    NODE_ELEMENT_HEIGHT,
    NODE_ELEMENT_WIDTH,
    LABEL_ELEMENT_HEIGHT,
    LABEL_ELEMENT_WIDTH,
};
